### PR TITLE
Added how we work and bills bio tweak

### PR DESCRIPTION
**Pull request by bilsch**
This is a bit of a rough cut but I wanted to get it out for views

### CODE REVIEW

**Review by MathematicsCLtd — COMMENTED** [review]
index.md
Important Links 
Community GitHub org link is broken.
Seed Use Cases bullet point *our own instead of own own

**Review by MathematicsCLtd — COMMENTED** [review]
Code of conduct, add an email address to Enforcement section.

**Review by vijayyadav06 — DISMISSED** [review]

**Comment by bilsch** [comment]
> Code of conduct, add an email address to Enforcement section.

For now lets leave the code of conduct bit alone thats a really good callout but we don't have an email alias / domain setup with this that we would all see. I'd like to explore setting something up - even a google form would be a good idea for that ( and probably easier )

**Comment by bilsch** [comment]
> index.md
> Important Links
> Community GitHub org link is broken.
> Seed Use Cases bullet point *our own instead of own own

thanks these are fixed now

**Review by vijayyadav06 — APPROVED** [review]

**Review by vijayyadav06 — APPROVED** [review]

**Pull request merged**
